name: Python CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Use the latest Python version (adjust as needed)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          make install

      # Step 4: Lint code with Pylint
      - name: Lint with Pylint
        run: |
          make lint

      # Step 5: Run tests with Pytest
      - name: Test with Pytest
        run: |
          make test

      # Step 6: Format code with Black
      - name: Format code with Black
        run: |
          make format

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRETE_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}
      # Step 7: Log in to AWS ECR
      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'
        
      # Step 8: Set up Docker build and tag
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_NAME }}:latest .
          docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

      # Step 4: Push Docker image to AWS ECR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

      # Step 5: Post-deployment (optional)
      - name: Deployment Success Notification
        run: echo "Docker image successfully deployed to AWS ECR!"
